import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>

        <form className='container'>
        <h2 className='title'>Entrar</h2>

        <input className='input' type='email' name='email' placeholder='Email' />

        <input className='input' type='password' name='password' placeholder='Password' />

        <button className='button' type='submit'>Entrar</button>

        <p>Novo aqui?<Link href="/cadastrar"> Crie uma conta</Link></p>

        </form>
      </main>
    </>
  )
}
